### PR TITLE
Added Support and Preference Options for common Content Media Types

### PR DESCRIPTION
**Pull request by Garmichael**
Added Support and Preference Options for common Content Media Types: Audio, Images, and 3D Assets

Also autoformatted the files with `Control+Alt+L` inside Rider

### CODE REVIEW

**Comment by van800** [comment]
It is a bad practice to mix formatting and real changes in one commit. Could you please split them?

**Comment by Garmichael** [comment]
I cleaned that in up in the last commit, titled "Refactored methods to be more DRY"

**Review by van800 — COMMENTED** [review]
It looks much better now, while one more thing could be done.
Pass {"json"} as an array also.

Update: Sorry, I was mistaken. Do not count this.

**Comment by Garmichael** [comment]
I refactored it anyway, so when adding a single item, it adds an array of one item instead. That way I only need the one method.

I decided to keep the variable declaration just because its easier to read than, say:

```
 AddFileExtensions(projectContentElement, xmlns, new string[]{"mp3", "wav", "ogg", "aiff", "aif", "mod", "it", "s3m", "xm"});
```

**Comment by van800** [comment]
I tried your code, added several json files to different places in file-structure. 
Modified 
`content.Add(new XAttribute("Include", @"**\*." + extension));`
to
`content.Add(new XAttribute("Include", @"Assets\**\*." + extension));`
and what bothers me, that each json file gets added to every Unity-generated csproj.

image

But I am not sure, how to fix it. Would it be fine to add them only to UNITY_PLAYER_PROJECT, which is Assembly-CSharp.csproj?

**Comment by van800** [comment]
Also I can't understand, why your formatting is different with mine. Do you have Editor Config and Rider Editor Configs plugins enabled?

**Comment by Garmichael** [comment]
That's something I don't understand in general... I would prefer to only see Assembly-CSharp.csproj. I'm not sure what the difference is between those tree roots. 

Also for the root vs /Assets thing.. I'm good with making it /Assets only.

My Editor config is the defaults for C# code style. It could maybe be that we just have different tab spacing and we both have tabs convert into space chars?

**Comment by van800** [comment]
First lets check if you have the plugins
image

**Comment by Garmichael** [comment]
Yep, both are installed and checked.

**Comment by van800** [comment]
There is a file .editorconfig in the root of Unity3dRider repo, and together with plugin it is expected to override Code Style settings. Aha, I have found one more checkbox "Enable editor config support", is it checked for you?
image

**Comment by Garmichael** [comment]
Yep, it is. For you when you do Control+Alt+L, it doesnt change it from your 2-space indenting?

I think most of the formatting that was done was just changing 2 spaces to 4 spaces, and then wrap lines that are too long.

**Comment by van800** [comment]
I have different shortcut scheme, but the action "Reformat code" changes indent back to 2.

**Comment by Garmichael** [comment]
I can just set my tabs to 2 until I'm done committing and it'll revert to your formatting style and check that in as a commit.

After that, I'll commit the /Assets thing.

But I've been looking over the code and I still don't quite get the whole Editor-firstpass project folder thing

**Comment by van800** [comment]
Have you managed to add empty folders to solution?

**Comment by Garmichael** [comment]
No I havent, and I don't have any idea how to do that. I googled around and saw some pretty complex stuff that I just don't know anything about. For now, I'm alright with the empty folders thing since if i add a new folder, it's added to the solution, and all my existing folders have something in them now that .json files are part of the solution

**Comment by van800** [comment]
"Editor-firstpass project folder thing" is something I am not considering to change, because it is a way that Unity does it and everybody seem fine with it.

**Comment by Garmichael** [comment]
Im alright with that. Just not sure yet how to keep the content files only in the `Assembly-CSharp` proj. I'll read over the code in the morning (it's 3am now).

Should I go ahead with the un-reformating (back to 2 spaces), and the "only in the Assets" folder commits?

**Comment by van800** [comment]
I have tried to do it, and for now stopped with filing a request to Rider https://youtrack.jetbrains.com/issue/RIDER-5588

**Comment by van800** [comment]
And I am really curious, why editor config didn't work for you...

**Comment by citizenmatt** [comment]
There is a Unity setting that allows listing extra file extensions to include in the project. It might be worth just using that setting, rather than adding extra code into this plugin?

You can set the extra file extensions in the Edit &rarr; Project Settings &rarr; Editor pane.

screen shot 2017-04-11 at 10 55 26 am

**Comment by Garmichael** [comment]
Oh brother, just tested it out and it works perfectly. It's hidden way out of the way!

So... i guess this whole pull request could be ditched. At least I learned a lot about tabs n spaces and github use/etiquette, heh. 

Thanks Matt for the easy answer, and Van for the help along the process.

**Comment by van800** [comment]
@Garmichael At least we both now know more about Unity.

**Pull request closed without merging**
